// COPYRIGHT Dassault Systemes 2019
//===================================================================
//
// IdentityCard.h
// Supplies the list of prerequisite components for framework CCETAndSInsulationLayerFrm
//
//===================================================================
//
// Usage notes:
//   For every prereq framework FW, use the syntax:
//   AddPrereqComponent ("FW", Public);
//
//===================================================================
//
//  Feb 2019  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
// DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
AddPrereqComponent("System",Protected);
AddPrereqComponent("ApplicationFrame",Protected);
AddPrereqComponent("DialogEngine",Protected);
AddPrereqComponent("Mathematics",Protected);
AddPrereqComponent("Dialog",Protected);
// END WIZARD EDITION ZONE
AddPrereqComponent("ObjectModelerBase",Protected);
AddPrereqComponent("MecModInterfaces",Protected);
AddPrereqComponent("ObjectSpecsModeler",Protected);
AddPrereqComponent("Visualization",Protected);
AddPrereqComponent("MechanicalModeler",Protected);
AddPrereqComponent("KnowledgeInterfaces",Protected);
AddPrereqComponent("GSMInterfaces",Protected);
AddPrereqComponent("NewTopologicalObjects",Protected);
AddPrereqComponent("MeasureGeometryInterfaces",Protected);
AddPrereqComponent("ProductStructure",Protected);
AddPrereqComponent("MechanicalCommands",Protected);
AddPrereqComponent("SpaceAnalysisInterfaces",Protected);
AddPrereqComponent("CATAssemblyInterfaces",Protected);
AddPrereqComponent("GeometricObjects",Protected);
AddPrereqComponent("PartInterfaces",Protected);
AddPrereqComponent("DraftingInterfaces",Protected);
AddPrereqComponent("SketcherInterfaces",Protected);
AddPrereqComponent("InteractiveInterfaces",Protected);
AddPrereqComponent("GSOInterfaces",Protected);
AddPrereqComponent("ProductStructureInterfaces",Protected);
AddPrereqComponent("VisualizationBase",Protected);
AddPrereqComponent("Dialog",Protected);
AddPrereqComponent("DialogEngine",Protected);
AddPrereqComponent("Mathematics",Protected);
AddPrereqComponent("MechanicalModelerUI",Protected);
