set ALLUSERSPROFILE=C:\ProgramData
set APPDATA=C:\Users\Administrator\AppData\Roaming
set BLD_HOST_OS=win_b64
set CATNoStartDocument=Yes
set CommonProgramFiles=C:\Program Files (x86)\Common Files
set CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
set CommonProgramW6432=C:\Program Files\Common Files
set COMPUTERNAME=WIN7-1803141441
set ComSpec=C:\Windows\system32\cmd.exe
set CorbaCppBuildROOT_PATH=\\ds\dsy\iona\Orbix3.3\win_b64
set CorbaCppROOT_PATH=\\ds\dsy\iona\Orbix3.3\win_b64
set CorbaJavaROOT_PATH=\\ds\dsy\iona\Orbix3.3\win_b64
set CSCSkipTestOfMapFileValidity=1
set DEVMGR_SHOW_DETAILS=1
set DSXDEVVISUALCOMPILERVERSION=1.0-1.4
set FP_NO_HOST_CHECK=NO
set getRADE=C:\Users\ADMINI~1\AppData\Local\Temp\getRADE7443.bat
set HOME=E:\GITHOME
set HOMEDRIVE=C:
set HOMEPATH=\Users\Administrator
set INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\include;C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\atlmfc\include;C:\Program Files\Microsoft SDKs\Windows\v6.0A\include;C:\DASSAU~1\B22_RADE\intel_a\.\tools\include\win_b64;C:\DASSAU~1\B22_RADE\intel_a\.\tools\include
set INTEL_DEV_REDIST=C:\Program Files (x86)\Common Files\Intel\Shared Libraries\
set JLMDeployROOT_PATH=C:\DASSAU~1\B22_RADE\intel_a\.\jlm\jlmdeploy65
set LIB=C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\lib\amd64;C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\atlmfc\lib\amd64;C:\Program Files\Microsoft SDKs\Windows\v6.0A\lib\x64;C:\Windows\Microsoft.NET\Framework64\v3.5;C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.5;C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.0;C:\Windows\Microsoft.NET\Framework64\v2.0.50727
set LOCALAPPDATA=C:\Users\Administrator\AppData\Local
set LOGONSERVER=\\WIN7-1803141441
set MIC_LD_LIBRARY_PATH=C:\Program Files (x86)\Common Files\Intel\Shared Libraries\compiler\lib\intel64_win_mic
set mkcsbuild=502211292
set mkcsClientMode=1
set mkcsINSTALL_PATH=C:\DASSAU~1\B22_RADE
set mkcsOS_Buildtime=win_b64
set mkcsOS_NAME=Windows_NT
set mkcsOS_Runtime=intel_a
set mkcsROOT_PATH=C:\DASSAU~1\B22_RADE\intel_a
set mkcsSHLIB_NAME=PATH
set mkcsSHLIB_PATH=C:\DASSAU~1\B22_RADE\intel_a\code\bin
set mkcsVERSION=5.22.0.11292 (built Wed, Oct 19, 2011 at 20:00)
set MkmkADDON_INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\include;C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\atlmfc\include;C:\Program Files\Microsoft SDKs\Windows\v6.0A\include;C:\DASSAU~1\B22_RADE\intel_a\.\tools\include\win_b64;C:\DASSAU~1\B22_RADE\intel_a\.\tools\include
set MkmkADDON_LEVEL=MK_CATIAVER=5 MK_BITMODE=64 MK_MSCVER=1500 MK_IFVER=1001011 MK_ORBIXCPP33 MK_ORBIXJAVA33
set MkmkADDON_LIB=C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\lib\amd64;C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\atlmfc\lib\amd64;C:\Program Files\Microsoft SDKs\Windows\v6.0A\lib\x64;C:\Windows\Microsoft.NET\Framework64\v3.5;C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.5;C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.0;C:\Windows\Microsoft.NET\Framework64\v2.0.50727
set MkmkADDON_PATH=C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\bin\amd64;C:\Program Files\Microsoft SDKs\Windows\v6.0A\bin\x64;C:\Windows\Microsoft.NET\Framework64\v3.5;C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.5;C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.0;C:\Windows\Microsoft.NET\Framework64\v2.0.50727;C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\IDE;C:\DASSAU~1\B22_RADE\intel_a\code\command
set MkmkBAD_MINITFLEVEL=4
set mkmkbuild=502211292
set MkmkDictionary_PATH=C:\DASSAU~1\B22_RADE\intel_a\code\dictionary
set MkmkExternalDS=External
set MkmkIC_PATH=C:\DASSAU~1\B22_RADE\intel_a\code\productIC
set MkmkIF101Internal=101.011
set MkmkINSTALL_PATH=C:\DASSAU~1\B22_RADE
set MkmkJDK16Internal=0_14
set MkmkMsgCatalog_PATH=C:\DASSAU~1\B22_RADE\intel_a\resources\msgcatalog
set MkmkMSNET30DIR=C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.0
set MkmkMSNET35DIR=C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.5
set MkmkMSProgramFiles32=C:\Program Files (x86)
set MkmkMSPSDKDIR=C:\Program Files\Microsoft SDKs\Windows\v6.0A
set MkmkMSVCDIR=C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC
set MkmkMSVCSHARPDIR=C:\Windows\Microsoft.NET\Framework64\v3.5
set MkmkMSVJSHARPDIR=C:\Windows\Microsoft.NET\Framework64\v2.0.50727
set MkmkMSVSBINDIR=C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\IDE
set MkmkMSVSTOOLSBINDIR=C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\Tools\Bin
set MkmkOS_BitMode=64
set MkmkOS_Buildtime=win_b64
set MkmkOS_DOC=DOC
set MkmkOS_NAME=Windows_NT
set MkmkOS_Runtime=intel_a
set MkmkOS_Type=Windows
set MkmkOS_VAR=win_b64
set MkmkPATH4TOOLS=C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\bin\amd64;C:\Program Files\Microsoft SDKs\Windows\v6.0A\bin\x64;C:\Windows\Microsoft.NET\Framework64\v3.5;C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.5;C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.0;C:\Windows\Microsoft.NET\Framework64\v2.0.50727;C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\IDE;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64_win\compiler;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;E:\app\admin\product\12.2.0\dbhome_1\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;c:\Program Files (x86)\Microsoft SQL Server\90\Tools\binn;C:\Program Files\Microsoft\Web Platform Installer;C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0;C:\Program Files (x86)\Windows Kits\8.0\Windows Performance Toolkit;C:\Program Files\Microsoft SQL Server\110\Tools\Binn;C:\Program Files\IDM Computer Solutions\UltraCompare;C:\Program Files\Git\cmd;C:\Program Files\TortoiseGit\bin;C:\DassaultSystemes\B22_RADE\intel_a\TCK\command
set MkmkReffiles_PATH=C:\DASSAU~1\B22_RADE\intel_a\reffiles
set MkmkRMSSDK_PATH=C:\DASSAU~1\B22_RADE\intel_a\.\rms\rmssdksp2
set MkmkROOTINSTALL_PATH=C:\DASSAU~1\B22_RADE\intel_a
set MkmkROOT_PATH=C:\DASSAU~1\B22_RADE\intel_a
set MkmkSHLIB_NAME=PATH
set MkmkSHLIB_PATH=C:\DASSAU~1\B22_RADE\intel_a\code\bin
set MkmkTOOLSINCLUDE_PATH=C:\DASSAU~1\B22_RADE\intel_a\.\tools\include\win_b64;C:\DASSAU~1\B22_RADE\intel_a\.\tools\include
set MkmkTOOLSLIB_PATH=C:\DASSAU~1\B22_RADE\intel_a\.\tools\lib
set MkmkVERSION=5.22.0.11292 (built Wed, Oct 19, 2011 at 20:00)
set MkmkVERSIONINFO=NO
set MkmkVS90Internal=yes
set MkmkXMLMANIFEST=NO
set MKMK_DISABLE_COMPATMANIFEST=yes
set Mkmk_Modifier=1578
set Mkmk_Modifier_BAD=16
set MKMK_USEDIRECTORIESCACHE=yes
set MKMK_USEPRECOMPIL=yes
set MkodtOS_Runtime=win_b64
set MK_DEVNULL=NUL
set MK_SEPARATOR=;
set MK_TEMPDIR=C:\Users\ADMINI~1\AppData\Local\Temp
set MSMPI_INC=C:\Program Files (x86)\Microsoft SDKs\MPI\Include\
set MSMPI_LIB32=C:\Program Files (x86)\Microsoft SDKs\MPI\Lib\x86\
set MSMPI_LIB64=C:\Program Files (x86)\Microsoft SDKs\MPI\Lib\x64\
set NO_LOCAL_DEFINITION_FOR_IID=yes
set NUMBER_OF_PROCESSORS=8
set OS=Windows_NT
set PATH=C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\bin\amd64;C:\Program Files\Microsoft SDKs\Windows\v6.0A\bin\x64;C:\Windows\Microsoft.NET\Framework64\v3.5;C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.5;C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.0;C:\Windows\Microsoft.NET\Framework64\v2.0.50727;C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\IDE;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64_win\compiler;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;E:\app\admin\product\12.2.0\dbhome_1\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;c:\Program Files (x86)\Microsoft SQL Server\90\Tools\binn;C:\Program Files\Microsoft\Web Platform Installer;C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0;C:\Program Files (x86)\Windows Kits\8.0\Windows Performance Toolkit;C:\Program Files\Microsoft SQL Server\110\Tools\Binn;C:\Program Files\IDM Computer Solutions\UltraCompare;C:\Program Files\Git\cmd;C:\Program Files\TortoiseGit\bin;C:\DassaultSystemes\B22_RADE\intel_a\TCK\command;C:\DASSAU~1\B22_RADE\intel_a\code\command;C:\DASSAU~1\B22_RADE\intel_a\code\command
set PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
set PROCESSOR_ARCHITECTURE=AMD64
set PROCESSOR_ARCHITEW6432=AMD64
set PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
set PROCESSOR_LEVEL=6
set PROCESSOR_REVISION=3c03
set ProgramData=C:\ProgramData
set ProgramFiles=C:\Program Files (x86)
set ProgramFiles(x86)=C:\Program Files (x86)
set ProgramW6432=C:\Program Files
set PROMPT=$P$G
set PSModulePath=C:\Windows\system32\WindowsPowerShell\v1.0\Modules\
set PUBLIC=C:\Users\Public
set RADECATSettingPath=C:\Users\Administrator\AppData\Roaming\DassaultSystemes\CATSettings\RADE
set RELEASEMANAGER_PATH=C:\DASSAU~1\B22_RADE\intel_a
set rtcode=0
set SESSIONNAME=Console
set SystemDrive=C:
set SystemRoot=C:\Windows
set TCKHelp=-
set TCKOS_Runtime=intel_a
set TCK_DATE=2018/03/14-16:06:44
set TCK_ID=V5_6R2012_B22
set TCK_INSTALL_PATH=C:\DassaultSystemes\B22_RADE
set TCK_LOCAL_INFO=C:\Program Files (x86)
set TCK_NAME=V5_6R2012_B22
set TCK_NO_SERVER=true
set TCK_ROOT_PATH=C:\DassaultSystemes\B22_RADE\intel_a
set TCK_TMP_FILE=C:\Users\ADMINI~1\AppData\Local\Temp\tckexec__Administrator_40962.bat
set TEMP=C:\Users\ADMINI~1\AppData\Local\Temp
set TMP=C:\Users\ADMINI~1\AppData\Local\Temp
set USERDOMAIN=WIN7-1803141441
set USERNAME=Administrator
set USERPROFILE=C:\Users\Administrator
set VBTtmp=C:\Users\ADMINI~1\AppData\Local\Temp
set VisualStudioDir=D:\UserData\Personal\Visual Studio 2008
set VS110COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\Tools\
set VS90COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\Tools\
set WecVersionForRosebud.2EA0=2
set windir=C:\Windows
set windows_tracing_flags=3
set windows_tracing_logfile=C:\BVTBin\Tests\installpackage\csilogfile.log
set _tck_exec=OK
set __COMPAT_LAYER=ElevateCreateProcess
