#include "CATIAfrGeneralWksAddin.h"
#include "CATCmdContainer.h"
#include "CATCreateWorkshop.h"
#include "CATDlgDialog.h"
#include "iostream.h"
#include "CATCollec.h"
#include "CATListOfCATUnicodeString.h"
#include "CATDocument.h"
#include "CATDocumentServices.h"
#include "CATInit.h"
#include "CATIPrtContainer.h"
#include "CATIPrtPart.h"
#include "CATISpecObject.h"
#include "CATIPartRequest.h"
#include "CATListOfCATBaseUnknown.h"
#include "CATIAlias.h"
#include "CATSession.h"
#include "CATSessionServices.h"
#include "CATIDescendants.h"
#include "CATIMechanicalRootFactory.h"
#include "CATIVisProperties.h"
#include "CATMmrInterPartCopy.h"
#include "CATLib.h"
#include "CATFeatureImportAgent.h"
#include "CATIBRepAccess.h"
#include "CATIFeaturize.h"
#include "CATIGSMFactory.h"
#include "CATIDatumFactory.h"
#include "CATICkeParmFactory.h"
#include "CATICkeFunctionFactory.h"
#include "CATIParmDictionary.h"
#include "CATICkeMagnitude.h"
#include "CATFrmEditor.h"
#include "CATCkeGlobalFunctions.h"
#include "CATIGSMIntersect.h"
#include "CATMfErrUpdate.h"
#include "CATError.h"
#include "CATIGSMPointOnCurve.h"
#include "CATICkeRelation.h"
#include "CATIGSMSplit.h"
#include "CATBody.h"
#include "CATCell.h"
#include "CATMfBRepDecode.h"
#include "CATIBRepAccess.h"
#include "CATIMfBRep.h"
#include "CATIMeasurableCurve.h"
#include "CATIMeasurablePoint.h"
#include "CATIMeasurablePlane.h"
#include "CATIMeasurableLine.h"

#include "CATIGSMCurveSmooth.h"
#include "CATIGSMBoundary.h"
#include "CATIGSMLinePtPt.h"
#include "CATIGSMProject.h"
#include "CATMathVectorf.h"
#include "CATMathPointf.h"
#include "CATCollec.h"
#include "CATListOfDouble.h"
#include "CATIDocRoots.h"
#include "CATIProduct.h"
#include "CATIGSMCircleBitangentRadius.h"

#include "CATIUdfFactory.h"
#include "CATIUdfInstantiate.h"

#include "CATIGSMLoft.h"

#include "CATIGSMLineNormal.h"
#include "CATIGSMInverse.h"

#include "CATLISTP_CATMathVector.h"

#include "CATEdge.h"
#include "CATEdgeCurve.h"
#include "CATIMeasurableInContext.h"

#include "CATIGSMPlane1Line1Pt.h"
#include "CATIGSMAssemble.h"

#include "CATLISTP_CATMathPoint.h"
#include "CATIGSMExtrapol.h"
#include "CATIGSMCurvePar.h"

#include "CATIGSMExtrude.h"

#include "CATIPrdObjectPublisher.h"
#include "CATIModelEvents.h"
#include "CATModify.h"
#include "CATIRedrawEvent.h"
#include "CATAsmConnectorServices.h"

#include "CATModifyVisProperties.h"

#include "CATFace.h"
#include "CATMmrApplicativeAttributes.h"
#include "CATIMfGeometryAccess.h"
#include "CATModifyVisProperties.h"

#include "CATIGSMPolyline.h"
#include "CATIGSMFill.h"
#include "CATIMechanicalFeature.h"
#include "CATIGSMPlaneNormal.h"
#include "CATIGSMLineBiTangent.h"

/////////////////////////////////////////
#include "CATDocumentServices.h"
#include "CATIDftDocumentServices.h"
#include "CATIDftDrawing.h"
#include "CATDocument.h"
#include "CATIDftStandardManager.h"
#include "CATIDftDrawingFormats.h"
#include "CATLISTV_CATISpecObject.h"
#include "CATIDftFormat.h"
#include "CATIDftSheetFormat.h"
#include "CATIDftSheet.h"
#include "CATSession.h"
#include "CATSessionServices.h"
#include "CATIIniInteractiveSession.h"
#include "CATIEditor.h"
#include "CATFrmEditor.h"
#include "CATIADrawingDocument.h"
#include "CATIAGenerativeViewBehavior.h"
#include "CATIView.h"
#include "CATIGenerSpec.h"
#include "CATIDftView.h"
#include "CATIDrwAnnotation.h"
#include "CATIUnknownList.h"
#include "CATIInstance.h"
#include "CAT3DViewpoint.h"
//*********************************
#include "CATIDftGenView.h"
#include "iostream.h"
#include "CATAutoConversions.h"
#include "CATIDrwFactory.h"
#include "CATIDftViewMakeUp.h"
#include "CATIDrawing.h"
#include "CATISheet.h"
#include "CATIDftGenView.h"
#include "CATMathBox2D.h"
#include "CATIGSMLineAngle.h"
#include "CATIGSMCircleCtrRad.h"
#include "CATIGSMNear.h"
//*********************************


#include "CATIGSMExtractSolide.h"
#include "CATIGSMUnfold.h"
#include "CATIGSOFactory.h"

#include "CATICst.h"

#include "CATIDrwAnnotationFactory.h"
#include "CATI2DWFFactory.h"
#include "CATIDftGenGeomAccess.h"
#include "CATIDftGenGeom.h"
#include "ListPOfCATBody.h"
#include "CATLISTPIUnknown.h"
#include "CATDimDefinition.h"
#include "CATIUnknownListImpl.h"
#include "CATIUnknownList.h"
#include "CATIGSMTool.h"
#include "CATIDrwDimDimensionLine.h"
#include "CATIDrwDimValue.h"
#include "CATIDrwDimValueComponent.h"
#include "CATIDrwDimTolerance.h"
#include "CATIDrwTextProperties.h"

#include "CATICutAndPastable.h"
#include "SpecBindNativeFormat.h"
#include "CATViewer.h"

#include "CATPoint.h"
#include "CATVertex.h"

#include "CATIMmiNonOrderedGeometricalSet.h"
#include "CATICkeRelationFactory.h"
#include "CATIGSMPointCoord.h"
#include "CATIGSMLinePtDir.h"
#include "CATIGSMTranslate.h"
#include "CATIGSMExtremum.h"
#include "CATIGSMCircleCtrPt.h"
#include "CATIGSMPointOnPlane.h"
#include "CATIRectPatt.h"
#include "CATIPrtFactory.h"
#include "CATICircPatt.h"
#include "CATIGSMCircle3Points.h"
#include "CATIGSMPointBetween.h"
#include "CATIGSMSpine.h"
#include "CATIGSMSpline.h"
#include "CATIGSMCircleBitangentPoint.h"
#include "CATIGSMCircleTritangent.h"
#include "CATIGSMCorner.h"


#include "CATIParmManipulator.h"

#include <vector>
#include <algorithm> // 包含通用算法


#ifdef _WINDOWS_
#undef _WINDOWS_
#include <afx.h>
#endif