// COPYRIGHT Dassault Systemes 2019
//===================================================================
//
// CCETAndSInsulationLayerTlb.cpp
// Provide implementation to interface
//    CATIAfrGeneralWksAddin
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//  Feb 2019  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
#include "CCETAndSInsulationLayerTlb.h"
#include "CATCommandHeader.h"
#include "CATCreateWorkshop.h"
 
CATImplementClass(CCETAndSInsulationLayerTlb,
                  Implementation,
                  CATBaseUnknown,
                  CATnull );
MacDeclareHeader(CCETAndSInsulationLayerHeader);

//TIE or TIEchain definitions
#include "TIE_CATIAfrGeneralWksAddin.h"
TIE_CATIAfrGeneralWksAddin(CCETAndSInsulationLayerTlb);
 

//-----------------------------------------------------------------------------
// CCETAndSInsulationLayerTlb : constructor
//-----------------------------------------------------------------------------
CCETAndSInsulationLayerTlb::CCETAndSInsulationLayerTlb():
    CATBaseUnknown()
{
}

//-----------------------------------------------------------------------------
// CCETAndSInsulationLayerTlb : destructor
//-----------------------------------------------------------------------------
CCETAndSInsulationLayerTlb::~CCETAndSInsulationLayerTlb()
{
}
 

void CCETAndSInsulationLayerTlb::CreateCommands()  
{
	//隔音棉创建
	new CCETAndSInsulationLayerHeader("FrameInSoundproofCottonGeneration","CCETAndSInsulationLayerOperationM","CCEFrameInSoundproofCottonGenerationCmd",(void *)NULL);//框上隔音棉生成
	new CCETAndSInsulationLayerHeader("FrameBetweenSoundproofCottonGeneration","CCETAndSInsulationLayerOperationM","CCEFrameBetweenSoundproofCottonGenerationCmd",(void *)NULL);//框间隔音棉生成
	new CCETAndSInsulationLayerHeader("ContractionFrameBetweenSoundproofCottonGeneration","CCETAndSInsulationLayerOperationM","CCEContractionFrameBetweenSoundproofCottonGenerationCmd",(void *)NULL);//收缩段框间隔音棉生成
	new CCETAndSInsulationLayerHeader("OpeningFeatureGeneration","CCETAndSInsulationLayerOperationM","CCEOpeningFeatureGenerationCmd",(void *)NULL);//开叉特征生成
	new CCETAndSInsulationLayerHeader("GrooveFeatureGeneration","CCETAndSInsulationLayerOperationM","CCEGrooveFeatureGenerationCmd",(void *)NULL);//开槽特征生成
	new CCETAndSInsulationLayerHeader("FrameInSoundproofCottonUnfold","CCETAndSInsulationLayerOperationM","CCEFrameInSoundproofCottonUnfoldCmd",(void *)NULL);//框上隔音棉展开
	new CCETAndSInsulationLayerHeader("FrameBetweenSoundproofCottonUnfold","CCETAndSInsulationLayerOperationM","CCEFrameBetweenSoundproofCottonUnfoldCmd",(void *)NULL);//框间隔音棉展开
	new CCETAndSInsulationLayerHeader("InstallationAndUnfoldUpdate","CCETAndSInsulationLayerOperationM","CCEInstallationAndUnfoldUpdateCmd",(void *)NULL);//安装状态及展开状态自动更新

	//紧固件安装
	new CCETAndSInsulationLayerHeader("FastenerDefinition","CCETAndSInsulationLayerOperationM","CCEFastenerDefinitionCmd",(void *)NULL);//紧固件定义
	new CCETAndSInsulationLayerHeader("FastenerModify","CCETAndSInsulationLayerOperationM","CCEFastenerModifyCmd",(void *)NULL);//紧固件修改
	new CCETAndSInsulationLayerHeader("FastenerInstantiation","CCETAndSInsulationLayerOperationM","CCEFastenerInstantiationCmd",(void *)NULL);//实例化紧固件装配

	//统计功能
	new CCETAndSInsulationLayerHeader("WeightStatistic","CCETAndSInsulationLayerOperationM","CCEWeightStatisticCmd",(void *)NULL);//重量统计
	new CCETAndSInsulationLayerHeader("MaterialUsingStatistic","CCETAndSInsulationLayerOperationM","CCEMaterialUsingStatisticCmd",(void *)NULL);//材料用量统计
	new CCETAndSInsulationLayerHeader("FastenerNumberStatistic","CCETAndSInsulationLayerOperationM","CCEFastenerNumberStatisticCmd",(void *)NULL);//紧固件数量统计

	//材料库管理
	new CCETAndSInsulationLayerHeader("MaterialLibSearch","CCETAndSInsulationLayerOperationM","CCEMaterialLibSearchCmd",(void *)NULL);//材料库查询
	new CCETAndSInsulationLayerHeader("MaterialLibAdd","CCETAndSInsulationLayerOperationM","CCEMaterialLibAddCmd",(void *)NULL);//材料库新增
	new CCETAndSInsulationLayerHeader("MaterialLibModify","CCETAndSInsulationLayerOperationM","CCMaterialLibModifyCmd",(void *)NULL);//材料库修改
	new CCETAndSInsulationLayerHeader("MaterialLibDelete","CCETAndSInsulationLayerOperationM","CCEMaterialLibDeleteCmd",(void *)NULL);//材料库删除

	//紧固件库管理
	new CCETAndSInsulationLayerHeader("FastenerLibSearch","CCETAndSInsulationLayerOperationM","CCEFastenerLibSearchCmd",(void *)NULL);//材料库查询
	new CCETAndSInsulationLayerHeader("FastenerLibAdd","CCETAndSInsulationLayerOperationM","CCEFastenerLibAddCmd",(void *)NULL);//材料库查询
	new CCETAndSInsulationLayerHeader("FastenerLibModify","CCETAndSInsulationLayerOperationM","CCEFastenerLibModifyCmd",(void *)NULL);//材料库查询
	new CCETAndSInsulationLayerHeader("FastenerLibDelete","CCETAndSInsulationLayerOperationM","CCEFastenerLibDeleteCmd",(void *)NULL);//材料库查询





}


// Link the implementation to its interface
// ---------------------------------------
CATCmdContainer * CCETAndSInsulationLayerTlb::CreateToolbars()
{
	NewAccess(CATCmdContainer, pCCEPartOperationTlb, CR929飞机隔热隔声层3D制图软件);
	AddToolbarView(pCCEPartOperationTlb, -1, Right); 

	
	//==========================菜单=============================//
	//Menu
	NewAccess(CATCmdContainer,pRootMenuContainer,RootMenuContainer);//顶层菜单的容器，不可见

	NewAccess(CATCmdContainer,pRootMenu,CR929飞机隔热隔声层3D制图软件);//顶层菜单
	SetAccessChild(pRootMenuContainer,pRootMenu);

	NewAccess(CATCmdContainer,pSoundproofCottonCreatioSubMenu,隔音棉创建);
	SetAccessChild(pRootMenu,pSoundproofCottonCreatioSubMenu);

		NewAccess(CATCmdStarter,pFrameInSoundproofCottonGenerationCmd,框上隔音棉生成);
		SetAccessCommand(pFrameInSoundproofCottonGenerationCmd,"FrameInSoundproofCottonGeneration");
		SetAccessChild(pSoundproofCottonCreatioSubMenu,pFrameInSoundproofCottonGenerationCmd);

		NewAccess(CATCmdStarter,pFrameBetweenSoundproofCottonGenerationCmd,框间隔音棉生成);
		SetAccessCommand(pFrameBetweenSoundproofCottonGenerationCmd,"FrameBetweenSoundproofCottonGeneration");
		SetAccessNext(pFrameInSoundproofCottonGenerationCmd,pFrameBetweenSoundproofCottonGenerationCmd);

		NewAccess(CATCmdStarter,pContractionFrameBetweenSoundproofCottonGenerationCmd,收缩段框间隔音棉生成);
		SetAccessCommand(pContractionFrameBetweenSoundproofCottonGenerationCmd,"ContractionFrameBetweenSoundproofCottonGeneration");
		SetAccessNext(pFrameBetweenSoundproofCottonGenerationCmd,pContractionFrameBetweenSoundproofCottonGenerationCmd);

		NewAccess(CATCmdStarter,pOpeningFeatureGenerationCmd,开叉特征生成);
		SetAccessCommand(pOpeningFeatureGenerationCmd,"OpeningFeatureGeneration");
		SetAccessNext(pContractionFrameBetweenSoundproofCottonGenerationCmd,pOpeningFeatureGenerationCmd);

		NewAccess(CATCmdStarter,pGrooveFeatureGenerationCmd,开槽特征生成);
		SetAccessCommand(pGrooveFeatureGenerationCmd,"GrooveFeatureGeneration");
		SetAccessNext(pOpeningFeatureGenerationCmd,pGrooveFeatureGenerationCmd);

		NewAccess(CATCmdStarter,pFrameInSoundproofCottonUnfoldCmd,框上隔音棉展开);
		SetAccessCommand(pFrameInSoundproofCottonUnfoldCmd,"FrameInSoundproofCottonUnfold");
		SetAccessNext(pGrooveFeatureGenerationCmd,pFrameInSoundproofCottonUnfoldCmd);

		NewAccess(CATCmdStarter,pFrameBetweenSoundproofCottonUnfoldCmd,框间隔音棉展开);
		SetAccessCommand(pFrameBetweenSoundproofCottonUnfoldCmd,"FrameBetweenSoundproofCottonUnfold");
		SetAccessNext(pFrameInSoundproofCottonUnfoldCmd,pFrameBetweenSoundproofCottonUnfoldCmd);

		NewAccess(CATCmdStarter,pInstallationAndUnfoldUpdateCmd,安装状态及展开状态自动更新);
		SetAccessCommand(pInstallationAndUnfoldUpdateCmd,"InstallationAndUnfoldUpdate");
		SetAccessNext(pFrameBetweenSoundproofCottonUnfoldCmd,pInstallationAndUnfoldUpdateCmd);

	NewAccess(CATCmdContainer,pFastenerInstallationSubMenu,紧固件安装);
	SetAccessNext(pSoundproofCottonCreatioSubMenu,pFastenerInstallationSubMenu);

		NewAccess(CATCmdStarter,pFastenerDefinitionCmd,紧固件定义);
		SetAccessCommand(pFastenerDefinitionCmd,"FastenerDefinition");
		SetAccessChild(pFastenerInstallationSubMenu,pFastenerDefinitionCmd);

		NewAccess(CATCmdStarter,pFastenerFastenerModifyCmd,紧固件修改);
		SetAccessCommand(pFastenerFastenerModifyCmd,"FastenerModify");
		SetAccessNext(pFastenerDefinitionCmd,pFastenerFastenerModifyCmd);

		NewAccess(CATCmdStarter,pFastenerInstantiationCmd,实例化紧固件装配);
		SetAccessCommand(pFastenerInstantiationCmd,"FastenerInstantiation");
		SetAccessNext(pFastenerFastenerModifyCmd,pFastenerInstantiationCmd);

	NewAccess(CATCmdContainer,pStatisticalFunctionSubMenu,统计功能);
	SetAccessNext(pFastenerInstallationSubMenu,pStatisticalFunctionSubMenu);

		NewAccess(CATCmdStarter,pWeightStatisticCmd,重量统计);
		SetAccessCommand(pWeightStatisticCmd,"WeightStatistic");
		SetAccessChild(pStatisticalFunctionSubMenu,pWeightStatisticCmd);

		NewAccess(CATCmdStarter,pMaterialUsingStatisticCmd,材料用量统计);
		SetAccessCommand(pMaterialUsingStatisticCmd,"MaterialUsingStatistic");
		SetAccessNext(pWeightStatisticCmd,pMaterialUsingStatisticCmd);

		NewAccess(CATCmdStarter,pFastenerNumberStatisticCmd,紧固件数量统计);
		SetAccessCommand(pFastenerNumberStatisticCmd,"FastenerNumberStatistic");
		SetAccessNext(pMaterialUsingStatisticCmd,pFastenerNumberStatisticCmd);

	NewAccess(CATCmdContainer,pMaterialLibManagementSubMenu,材料库管理);
	SetAccessNext(pStatisticalFunctionSubMenu,pMaterialLibManagementSubMenu);//

		NewAccess(CATCmdStarter,pMaterialLibSearchCmd,材料库查询);
		SetAccessCommand(pMaterialLibSearchCmd,"MaterialLibSearch");
		SetAccessChild(pMaterialLibManagementSubMenu,pMaterialLibSearchCmd);

		NewAccess(CATCmdStarter,pMaterialLibAddCmd,材料库新增);
		SetAccessCommand(pMaterialLibAddCmd,"MaterialLibAdd");
		SetAccessNext(pMaterialLibSearchCmd,pMaterialLibAddCmd);

		NewAccess(CATCmdStarter,pMaterialLibModifyCmd,材料库修改);
		SetAccessCommand(pMaterialLibModifyCmd,"MaterialLibModify");
		SetAccessNext(pMaterialLibAddCmd,pMaterialLibModifyCmd);

		NewAccess(CATCmdStarter,pMaterialLibDeleteCmd,材料库删除);
		SetAccessCommand(pMaterialLibDeleteCmd,"MaterialLibDelete");
		SetAccessNext(pMaterialLibModifyCmd,pMaterialLibDeleteCmd);

	NewAccess(CATCmdContainer,pFastenerLibManagementSubMenu,紧固件库管理);
	SetAccessNext(pMaterialLibManagementSubMenu,pFastenerLibManagementSubMenu);

		NewAccess(CATCmdStarter,pFastenerLibSearchCmd,紧固件库查询);
		SetAccessCommand(pFastenerLibSearchCmd,"FastenerLibSearch");
		SetAccessChild(pFastenerLibManagementSubMenu,pFastenerLibSearchCmd);

		NewAccess(CATCmdStarter,pFastenerLibAddCmd,紧固件库新增);
		SetAccessCommand(pFastenerLibAddCmd,"FastenerLibAdd");
		SetAccessNext(pFastenerLibSearchCmd,pFastenerLibAddCmd);

		NewAccess(CATCmdStarter,pFastenerLibModifyCmd,紧固件库修改);
		SetAccessCommand(pFastenerLibModifyCmd,"FastenerLibModify");
		SetAccessNext(pFastenerLibAddCmd,pFastenerLibModifyCmd);

		NewAccess(CATCmdStarter,pFastenerLibDeleteCmd,紧固件库删除);
		SetAccessCommand(pFastenerLibDeleteCmd,"FastenerLibDelete");
		SetAccessNext(pFastenerLibModifyCmd,pFastenerLibDeleteCmd);

	






	SetAddinMenu(pCCEPartOperationTlb,pRootMenuContainer);



	

	return pCCEPartOperationTlb;
}







//Methods implementation

