// COPYRIGHT Dassault Systemes 2019
//===================================================================
//
// CCEFrameInSoundproofCottonGenerationDlg.h
// The dialog : CCEFrameInSoundproofCottonGenerationDlg
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   DIALOG
//End CAA2 Wizard Generation Report
//
//  Feb 2019  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
#ifndef CCEFrameInSoundproofCottonGenerationDlg_H
#define CCEFrameInSoundproofCottonGenerationDlg_H

#include "CATDlgDialog.h"
#include "CATDlgInclude.h"

//----------------------------------------------------------------------

/**
 * Describe the purpose of your panel here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 * <p>
 * refer to programming resources of Dialog framework.
 * (consult base class description).
 */
class CCEFrameInSoundproofCottonGenerationDlg: public CATDlgDialog
{
  // Allows customization/internationalization of command's messages
  // ---------------------------------------------------------------
  DeclareResource( CCEFrameInSoundproofCottonGenerationDlg, CATDlgDialog )

  public:

  CCEFrameInSoundproofCottonGenerationDlg();
  virtual ~CCEFrameInSoundproofCottonGenerationDlg();

  void Build ();


  protected:

  private:


//CAA2 WIZARD WIDGET DECLARATION SECTION
 CATDlgFrame*      _Frame001;
 CATDlgLabel*      _Label002;
 CATDlgLabel*      _Label004;
 CATDlgLabel*      _Label006;
 CATDlgEditor*      _Editor007;
 CATDlgEditor*      _Editor008;
 CATDlgEditor*      _Editor009;
 CATDlgFrame*      _Frame010;
 CATDlgLabel*      _Label011;
 CATDlgEditor*      _Editor012;
 CATDlgLabel*      _Label013;
 CATDlgEditor*      _Editor014;
 CATDlgFrame*      _Frame021;
 CATDlgLabel*      _Label022;
 CATDlgEditor*      _Editor023;
 CATDlgFrame*      _Frame024;
 CATDlgLabel*      _Label025;
 CATDlgEditor*      _Editor026;
 CATDlgLabel*      _Label027;
 CATDlgCombo*      _Combo028;
 CATDlgLabel*      _Label029;
 CATDlgLabel*      _Label030;
 CATDlgLabel*      _Label031;
 CATDlgLabel*      _Label032;
 CATDlgEditor*      _Editor033;
 CATDlgEditor*      _Editor034;
 CATDlgEditor*      _Editor035;
 CATDlgEditor*      _Editor036;
 CATDlgLabel*      _Label037;
 CATDlgLabel*      _Label039;
 CATDlgLabel*      _Label040;
 CATDlgLabel*      _Label041;
 CATDlgCombo*      _Combo042;
 CATDlgCombo*      _Combo043;
 CATDlgCombo*      _Combo044;
 CATDlgCombo*      _Combo045;
 CATDlgFrame*      _Frame015;
 CATDlgLabel*      _Label016;
 CATDlgCombo*      _Combo017;
 CATDlgLabel*      _Label018;
 CATDlgCombo*      _Combo019;
//END CAA2 WIZARD WIDGET DECLARATION SECTION


//END CAA2 WIZARD WIDGET DECLARATION SECTION
};

//----------------------------------------------------------------------

#endif
