// COPYRIGHT Dassault Systemes 2019
//===================================================================
//
// CCEFrameInSoundproofCottonGenerationDlg.cpp
// The dialog : CCEFrameInSoundproofCottonGenerationDlg
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Feb 2019  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
#include "CCEFrameInSoundproofCottonGenerationDlg.h"
#include "CATApplicationFrame.h"
#include "CATDlgGridConstraints.h"
#include "CATMsgCatalog.h"
#ifdef CCEFrameInSoundproofCottonGenerationDlg_ParameterEditorInclude
#include "CATIParameterEditorFactory.h"
#include "CATIParameterEditor.h"
#include "CATICkeParm.h"
#endif




//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
CCEFrameInSoundproofCottonGenerationDlg::CCEFrameInSoundproofCottonGenerationDlg() :
  CATDlgDialog ((CATApplicationFrame::GetApplicationFrame())->GetMainWindow(),
//CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
"CCEFrameInSoundproofCottonGenerationDlg",CATDlgWndBtnOKCancel|CATDlgGridLayout
//END CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
                               )
{
//CAA2 WIZARD CONSTRUCTOR INITIALIZATION SECTION
 _Frame001 = NULL;
 _Label002 = NULL;
 _Label004 = NULL;
 _Label006 = NULL;
 _Editor007 = NULL;
 _Editor008 = NULL;
 _Editor009 = NULL;
 _Frame010 = NULL;
 _Label011 = NULL;
 _Editor012 = NULL;
 _Label013 = NULL;
 _Editor014 = NULL;
 _Frame021 = NULL;
 _Label022 = NULL;
 _Editor023 = NULL;
 _Frame024 = NULL;
 _Label025 = NULL;
 _Editor026 = NULL;
 _Label027 = NULL;
 _Combo028 = NULL;
 _Label029 = NULL;
 _Label030 = NULL;
 _Label031 = NULL;
 _Label032 = NULL;
 _Editor033 = NULL;
 _Editor034 = NULL;
 _Editor035 = NULL;
 _Editor036 = NULL;
 _Label037 = NULL;
 _Label039 = NULL;
 _Label040 = NULL;
 _Label041 = NULL;
 _Combo042 = NULL;
 _Combo043 = NULL;
 _Combo044 = NULL;
 _Combo045 = NULL;
 _Frame015 = NULL;
 _Label016 = NULL;
 _Combo017 = NULL;
 _Label018 = NULL;
 _Combo019 = NULL;
//END CAA2 WIZARD CONSTRUCTOR INITIALIZATION SECTION
}

//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
CCEFrameInSoundproofCottonGenerationDlg::~CCEFrameInSoundproofCottonGenerationDlg()
{
//  Do not delete the control elements of your dialog: 
//     this is done automatically
//  --------------------------------------------------
//CAA2 WIZARD DESTRUCTOR DECLARATION SECTION
 _Frame001 = NULL;
 _Label002 = NULL;
 _Label004 = NULL;
 _Label006 = NULL;
 _Editor007 = NULL;
 _Editor008 = NULL;
 _Editor009 = NULL;
 _Frame010 = NULL;
 _Label011 = NULL;
 _Editor012 = NULL;
 _Label013 = NULL;
 _Editor014 = NULL;
 _Frame021 = NULL;
 _Label022 = NULL;
 _Editor023 = NULL;
 _Frame024 = NULL;
 _Label025 = NULL;
 _Editor026 = NULL;
 _Label027 = NULL;
 _Combo028 = NULL;
 _Label029 = NULL;
 _Label030 = NULL;
 _Label031 = NULL;
 _Label032 = NULL;
 _Editor033 = NULL;
 _Editor034 = NULL;
 _Editor035 = NULL;
 _Editor036 = NULL;
 _Label037 = NULL;
 _Label039 = NULL;
 _Label040 = NULL;
 _Label041 = NULL;
 _Combo042 = NULL;
 _Combo043 = NULL;
 _Combo044 = NULL;
 _Combo045 = NULL;
 _Frame015 = NULL;
 _Label016 = NULL;
 _Combo017 = NULL;
 _Label018 = NULL;
 _Combo019 = NULL;
//END CAA2 WIZARD DESTRUCTOR DECLARATION SECTION
}



void CCEFrameInSoundproofCottonGenerationDlg::Build()
{
//  TODO: This call builds your dialog from the layout declaration file
//  -------------------------------------------------------------------

//CAA2 WIZARD WIDGET CONSTRUCTION SECTION
 _Frame001 = new CATDlgFrame(this, "Frame001", CATDlgFraNoTitle|CATDlgGridLayout);
_Frame001 -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _Label002 = new CATDlgLabel(_Frame001, "Label002");
_Label002 -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _Label004 = new CATDlgLabel(_Frame001, "Label004");
_Label004 -> SetGridConstraints(1, 0, 1, 1, CATGRID_4SIDES);
 _Label006 = new CATDlgLabel(_Frame001, "Label006");
_Label006 -> SetGridConstraints(2, 0, 1, 1, CATGRID_4SIDES);
 _Editor007 = new CATDlgEditor(_Frame001, "Editor007");
_Editor007 -> SetGridConstraints(2, 1, 1, 1, CATGRID_4SIDES);
 _Editor008 = new CATDlgEditor(_Frame001, "Editor008");
_Editor008 -> SetGridConstraints(0, 1, 1, 1, CATGRID_4SIDES);
 _Editor009 = new CATDlgEditor(_Frame001, "Editor009");
_Editor009 -> SetGridConstraints(1, 1, 1, 1, CATGRID_4SIDES);
 _Frame010 = new CATDlgFrame(this, "Frame010", CATDlgGridLayout);
_Frame010 -> SetGridConstraints(1, 0, 1, 1, CATGRID_4SIDES);
 _Label011 = new CATDlgLabel(_Frame010, "Label011");
_Label011 -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _Editor012 = new CATDlgEditor(_Frame010, "Editor012");
_Editor012 -> SetGridConstraints(0, 1, 1, 1, CATGRID_4SIDES);
 _Label013 = new CATDlgLabel(_Frame010, "Label013");
_Label013 -> SetGridConstraints(1, 0, 1, 1, CATGRID_4SIDES);
 _Editor014 = new CATDlgEditor(_Frame010, "Editor014");
_Editor014 -> SetGridConstraints(1, 1, 1, 1, CATGRID_4SIDES);
 _Frame021 = new CATDlgFrame(this, "Frame021", CATDlgFraNoTitle|CATDlgGridLayout);
_Frame021 -> SetGridConstraints(3, 0, 1, 1, CATGRID_4SIDES);
 _Label022 = new CATDlgLabel(_Frame021, "Label022");
_Label022 -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _Editor023 = new CATDlgEditor(_Frame021, "Editor023");
_Editor023 -> SetGridConstraints(0, 1, 1, 1, CATGRID_4SIDES);
 _Frame024 = new CATDlgFrame(this, "Frame024", CATDlgGridLayout);
_Frame024 -> SetGridConstraints(4, 0, 1, 1, CATGRID_4SIDES);
 _Label025 = new CATDlgLabel(_Frame024, "Label025");
_Label025 -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _Editor026 = new CATDlgEditor(_Frame024, "Editor026");
_Editor026 -> SetGridConstraints(0, 1, 1, 1, CATGRID_4SIDES);
 _Label027 = new CATDlgLabel(_Frame024, "Label027");
_Label027 -> SetGridConstraints(0, 2, 1, 1, CATGRID_4SIDES);
 _Combo028 = new CATDlgCombo(_Frame024, "Combo028", CATDlgCmbDropDown);
_Combo028 -> SetGridConstraints(0, 3, 1, 1, CATGRID_4SIDES);
 _Label029 = new CATDlgLabel(_Frame024, "Label029");
_Label029 -> SetGridConstraints(1, 0, 1, 1, CATGRID_4SIDES);
 _Label030 = new CATDlgLabel(_Frame024, "Label030");
_Label030 -> SetGridConstraints(2, 0, 1, 1, CATGRID_4SIDES);
 _Label031 = new CATDlgLabel(_Frame024, "Label031");
_Label031 -> SetGridConstraints(3, 0, 1, 1, CATGRID_4SIDES);
 _Label032 = new CATDlgLabel(_Frame024, "Label032");
_Label032 -> SetGridConstraints(4, 0, 1, 1, CATGRID_4SIDES);
 _Editor033 = new CATDlgEditor(_Frame024, "Editor033");
_Editor033 -> SetGridConstraints(1, 1, 1, 1, CATGRID_4SIDES);
 _Editor034 = new CATDlgEditor(_Frame024, "Editor034");
_Editor034 -> SetGridConstraints(2, 1, 1, 1, CATGRID_4SIDES);
 _Editor035 = new CATDlgEditor(_Frame024, "Editor035");
_Editor035 -> SetGridConstraints(3, 1, 1, 1, CATGRID_4SIDES);
 _Editor036 = new CATDlgEditor(_Frame024, "Editor036");
_Editor036 -> SetGridConstraints(4, 1, 1, 1, CATGRID_4SIDES);
 _Label037 = new CATDlgLabel(_Frame024, "Label037");
_Label037 -> SetGridConstraints(1, 2, 1, 1, CATGRID_4SIDES);
 _Label039 = new CATDlgLabel(_Frame024, "Label039");
_Label039 -> SetGridConstraints(2, 2, 1, 1, CATGRID_4SIDES);
 _Label040 = new CATDlgLabel(_Frame024, "Label040");
_Label040 -> SetGridConstraints(3, 2, 1, 1, CATGRID_4SIDES);
 _Label041 = new CATDlgLabel(_Frame024, "Label041");
_Label041 -> SetGridConstraints(4, 2, 1, 1, CATGRID_4SIDES);
 _Combo042 = new CATDlgCombo(_Frame024, "Combo042", CATDlgCmbDropDown);
_Combo042 -> SetGridConstraints(1, 3, 1, 1, CATGRID_4SIDES);
 _Combo043 = new CATDlgCombo(_Frame024, "Combo043", CATDlgCmbDropDown);
_Combo043 -> SetGridConstraints(2, 3, 1, 1, CATGRID_4SIDES);
 _Combo044 = new CATDlgCombo(_Frame024, "Combo044", CATDlgCmbDropDown);
_Combo044 -> SetGridConstraints(3, 3, 1, 1, CATGRID_4SIDES);
 _Combo045 = new CATDlgCombo(_Frame024, "Combo045", CATDlgCmbDropDown);
_Combo045 -> SetGridConstraints(4, 3, 1, 1, CATGRID_4SIDES);
 _Frame015 = new CATDlgFrame(this, "Frame015", CATDlgGridLayout);
_Frame015 -> SetGridConstraints(2, 0, 1, 1, CATGRID_4SIDES);
 _Label016 = new CATDlgLabel(_Frame015, "Label016");
_Label016 -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _Combo017 = new CATDlgCombo(_Frame015, "Combo017", CATDlgCmbDropDown);
_Combo017 -> SetGridConstraints(0, 1, 1, 1, CATGRID_4SIDES);
 _Label018 = new CATDlgLabel(_Frame015, "Label018");
_Label018 -> SetGridConstraints(1, 0, 1, 1, CATGRID_4SIDES);
 _Combo019 = new CATDlgCombo(_Frame015, "Combo019", CATDlgCmbDropDown);
_Combo019 -> SetGridConstraints(1, 1, 1, 1, CATGRID_4SIDES);
//END CAA2 WIZARD WIDGET CONSTRUCTION SECTION

//CAA2 WIZARD CALLBACK DECLARATION SECTION
//END CAA2 WIZARD CALLBACK DECLARATION SECTION

}

